"""
pipeline.py — Main orchestrator for the Daily Finance Newspaper.

Runs the full pipeline: fetch news → rewrite in plain English → 
render HTML + PDF → send email.

Usage:
    python src/pipeline.py                # Generate today's edition
    python src/pipeline.py --date 2026-07-11  # Generate for a specific date
    python src/pipeline.py --no-email     # Skip email delivery
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

# Add project root to path
PROJECT_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from dotenv import load_dotenv

# Load .env file with override=True to prioritize local values
load_dotenv(PROJECT_ROOT / ".env", override=True)

from src.news_fetcher import fetch_news
from src.news_rewriter import rewrite_stories
from src.pdf_generator import generate_pdf, generate_html
from src.emailer import send_newspaper_email


def get_edition_number(date_iso: str) -> int:
    """
    Calculate the edition number based on the date.
    Edition 1 = 2026-07-11 (first edition).
    """
    epoch = datetime(2026, 7, 11)
    current = datetime.strptime(date_iso, "%Y-%m-%d")
    delta = (current - epoch).days
    return max(1, delta + 1)


def build_template_context(stories: list[dict], date_iso: str) -> dict:
    """
    Build the Jinja2 template context from rewritten stories.
    
    Args:
        stories: List of rewritten story dicts (sorted by importance).
        date_iso: ISO date string (YYYY-MM-DD).
        
    Returns:
        Template context dict ready for rendering.
    """
    dt = datetime.strptime(date_iso, "%Y-%m-%d")
    date_readable = dt.strftime("%A, %B %d, %Y")
    
    # Lead story is the #1 ranked story
    lead_story = stories[0] if stories else None
    
    # Group remaining stories by section
    sections = {
        "markets": [],
        "economy": [],
        "companies": [],
        "explainer": [],
    }
    
    remaining_stories = stories[1:] if len(stories) > 1 else []
    for story in remaining_stories:
        category = story.get("category", "companies")
        if category in sections:
            sections[category].append(story)
        else:
            sections["companies"].append(story)
    
    return {
        "date": date_readable,
        "date_iso": date_iso,
        "edition_number": get_edition_number(date_iso),
        "newspaper_name": "THE DAILY FINANCE BRIEF",
        "tagline": "Financial News in Plain English",
        "lead_story": lead_story,
        "sections": sections,
        "all_stories": stories,
        "disclaimer": "Generated by AI · Not financial advice",
    }


def run_pipeline(
    date_iso: str | None = None,
    send_email: bool = True,
    html_base_url: str | None = None,
) -> dict:
    """
    Run the full newspaper generation pipeline.
    
    Args:
        date_iso: ISO date string. Defaults to today.
        send_email: Whether to send the email. Defaults to True.
        html_base_url: Base URL for the hosted HTML version.
        
    Returns:
        Dict with paths to generated files and metadata.
    """
    if date_iso is None:
        date_iso = datetime.now().strftime("%Y-%m-%d")
    
    print(f"{'='*60}")
    print(f"📰 THE DAILY FINANCE BRIEF — {date_iso}")
    print(f"{'='*60}")
    
    # Set up output directory
    output_dir = PROJECT_ROOT / "output" / date_iso
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Also create/update a 'latest' symlink
    latest_dir = PROJECT_ROOT / "output" / "latest"
    if latest_dir.is_symlink():
        latest_dir.unlink()
    elif latest_dir.exists():
        import shutil
        shutil.rmtree(latest_dir)
    latest_dir.symlink_to(output_dir.resolve())
    
    # Step 1: Fetch news
    print("\n🔍 Step 1/5: Fetching today's financial news...")
    raw_stories = fetch_news(date_iso)
    print(f"   Found {len(raw_stories)} stories")
    for s in raw_stories:
        print(f"   • [{s['category'].upper()}] {s['headline']}")
    
    # Step 2: Rewrite in plain English
    print("\n✍️  Step 2/5: Rewriting stories in plain English...")
    stories = rewrite_stories(raw_stories)
    print(f"   Rewritten {len(stories)} stories")
    
    # Save raw data for debugging/archiving
    data_path = output_dir / "data.json"
    with open(data_path, "w", encoding="utf-8") as f:
        json.dump({
            "date": date_iso,
            "raw_stories": raw_stories,
            "rewritten_stories": stories,
        }, f, indent=2, ensure_ascii=False)
    print(f"   Data saved to {data_path}")
    
    # Step 3: Build template context
    print("\n🎨 Step 3/5: Building newspaper layout...")
    context = build_template_context(stories, date_iso)
    
    # Step 4: Generate HTML and PDF
    html_path = str(output_dir / "index.html")
    pdf_path = str(output_dir / "daily_finance_brief.pdf")
    
    print("\n📄 Step 4/5: Generating HTML and PDF...")
    generate_html(context, html_path)
    
    try:
        generate_pdf(context, pdf_path)
    except Exception as e:
        print(f"   ⚠️  PDF generation failed: {e}")
        print(f"   HTML is still available at {html_path}")
        pdf_path = None
    
    # Step 5: Send email
    print("\n📧 Step 5/5: Sending email...")
    html_url = None
    if html_base_url:
        html_url = f"{html_base_url.rstrip('/')}/output/latest/index.html"
    
    email_sent = False
    if send_email and pdf_path:
        email_sent = send_newspaper_email(
            pdf_path=pdf_path,
            html_url=html_url,
            stories=stories,
            date=context["date"],
        )
    elif not send_email:
        print("   Skipping email (--no-email flag)")
    
    # Summary
    print(f"\n{'='*60}")
    print(f"✅ EDITION #{context['edition_number']} COMPLETE")
    print(f"{'='*60}")
    print(f"   HTML: {html_path}")
    if pdf_path:
        print(f"   PDF:  {pdf_path}")
    print(f"   Data: {data_path}")
    if email_sent:
        print(f"   📧 Email sent!")
    print()
    
    return {
        "html_path": html_path,
        "pdf_path": pdf_path,
        "data_path": str(data_path),
        "email_sent": email_sent,
        "edition_number": context["edition_number"],
        "story_count": len(stories),
    }


def main():
    parser = argparse.ArgumentParser(
        description="Generate the Daily Finance Brief newspaper"
    )
    parser.add_argument(
        "--date",
        type=str,
        default=None,
        help="Date to generate for (YYYY-MM-DD). Defaults to today.",
    )
    parser.add_argument(
        "--no-email",
        action="store_true",
        help="Skip email delivery.",
    )
    parser.add_argument(
        "--html-base-url",
        type=str,
        default=os.environ.get("HTML_BASE_URL"),
        help="Base URL for the hosted HTML version.",
    )
    
    args = parser.parse_args()
    
    result = run_pipeline(
        date_iso=args.date,
        send_email=not args.no_email,
        html_base_url=args.html_base_url,
    )
    
    # Exit with error if nothing was generated
    if not result.get("html_path"):
        sys.exit(1)


if __name__ == "__main__":
    main()
